# Electric Vehicle Population Data — Data Cleaning & Analysis Practical

## PART A — IMPORTING & UNDERSTANDING THE DATA

### Task 1 — Import the dataset

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("EVDataSet.csv")
df.head(5)

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJ3E1EA5L,Yakima,Yakima,WA,98908.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,266.0,14.0,102765120,POINT (-120.60272 46.59656),PACIFICORP,5.307700e+10
1,5YJ3E1EA9K,Thurston,Olympia,WA,98502.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220.0,22.0,326796641,POINT (-122.92018 47.04575),PUGET SOUND ENERGY INC,5.306701e+10
2,5YJSA1H22F,Kitsap,Kingston,WA,98346.0,2015,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,208.0,23.0,166294418,POINT (-122.4977 47.79802),PUGET SOUND ENERGY INC,5.303509e+10
3,KM8K33AG7L,King,Seattle,WA,98107.0,2020,HYUNDAI,KONA,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,258.0,43.0,127090015,POINT (-122.38591 47.67597),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
4,5YJ3E1EB1K,Yakima,Yakima,WA,98902.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220.0,14.0,272512824,POINT (-120.51904 46.59782),PACIFICORP,5.307700e+10

Each row represents one electrical vehical record registerd in a state.\
Each column represents feature describing that vehicle.

### Task 2 — Inspect the dataset structure

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294193 entries, 0 to 294192
Data columns (total 16 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         294193 non-null  object
 1   County                                             294183 non-null  object
 2   City                                               294183 non-null  object
 3   State                                              294193 non-null  object
 4   Postal Code                                        294183 non-null  float64
 5   Model Year                                         294193 non-null  int64
 6   Make                                               294193 non-null  object
 7   Model                                              294193 non-null  object
 8   Electric Vehicle Type                              294193 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  294193 non-null  object
 10  Electric Range                                     294180 non-null  float64
 11  Legislative District                               293431 non-null  float64
 12  DOL Vehicle ID                                     294193 non-null  int64
 13  Vehicle Location                                   294175 non-null  object
 14  Electric Utility                                   294183 non-null  object
 15  2020 Census Tract                                  294183 non-null  float64
dtypes: float64(4), int64(2), object(10)
memory usage: 35.9+ MB

In [4]:
df.describe()

,Postal Code,Model Year,Electric Range,Legislative District,DOL Vehicle ID,2020 Census Tract
count,294183.000000,294193.000000,294180.000000,293431.000000,2.941930e+05,2.941830e+05
mean,98176.263231,2022.312665,36.922578,28.766582,2.504942e+08,5.296843e+10
std,2644.315758,3.085205,76.309809,14.892012,6.244728e+07,1.674636e+09
min,1030.000000,1999.000000,0.000000,1.000000,4.385000e+03,1.001020e+09
25%,98052.000000,2021.000000,0.000000,17.000000,2.278658e+08,5.303301e+10
50%,98134.000000,2023.000000,0.000000,32.000000,2.675898e+08,5.303303e+10
75%,98390.000000,2024.000000,32.000000,42.000000,2.834127e+08,5.305394e+10
max,99801.000000,2027.000000,337.000000,49.000000,4.791150e+08,6.601095e+10

In [5]:
df["2020 Census Tract"].nunique()

2445

Identifier or code columns = VID, DOL Vehicle ID\
categorical = country, city, state, Postal code, Make, Model, Electric Vehicle Type, Clean Alternative Fuel Vehicle (CAFV) Eligibility, Legislative District, Electric Utility, 2020 Census Tract\
Numerical = Electric Range, Vehicle Location\
Date = Model Year

### Task 3 — Understand the dataset before cleaning

1. Which column identifies the vehicle manufacturer? ans: Make
2. Which column identifies the vehicle model? ans: Model
3. Which column represents the type of electric vehicle? ans: Electric Vehicle Type
4. Which columns describe location? ans: Vehicle Location
5. Which columns contain information related to electric range or vehicle price? ans: Electric Range
6. Which column represents the model year? ans: Model Year

## PART B — MISSING VALUES

### Task 4 — Find missing values

In [6]:
df.isnull().sum()

VIN (1-10)                                             0
County                                                10
City                                                  10
State                                                  0
Postal Code                                           10
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                        13
Legislative District                                 762
DOL Vehicle ID                                         0
Vehicle Location                                      18
Electric Utility                                      10
2020 Census Tract                                     10
dtype: int64

### Task 5 — Calculate missing-value percentages

In [7]:
percentage = df.isnull().mean() * 100

In [8]:
percentage

VIN (1-10)                                           0.000000
County                                               0.003399
City                                                 0.003399
State                                                0.000000
Postal Code                                          0.003399
Model Year                                           0.000000
Make                                                 0.000000
Model                                                0.000000
Electric Vehicle Type                                0.000000
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0.000000
Electric Range                                       0.004419
Legislative District                                 0.259014
DOL Vehicle ID                                       0.000000
Vehicle Location                                     0.006118
Electric Utility                                     0.003399
2020 Census Tract                                    0.003399
dtype: float64

### Task 6 — Decide how to handle missing values

Country = mode
City = mode
State = mode
Postal Code = mode
Electric Range = median
Legislative District = mode
Vehicle Location= mode
Electric Utility = mode
2020 Census Tract = median

### Task 7 — Handle numerical missing values and Task 8 — Handle categorical missing values

In [9]:
df["2020 Census Tract"] = df["2020 Census Tract"].fillna(value=df["2020 Census Tract"].mode()[0])
df["Electric Range"] = df["Electric Range"].fillna(value=df["Electric Range"].median())

In [10]:
df["County"] = df["County"].fillna(value=df["County"].mode()[0])
df["City"] = df["City"].fillna(value=df["City"].mode()[0])

In [11]:
df["Postal Code"] = df["Postal Code"].fillna(value=df["Postal Code"].mode()[0])
df["Vehicle Location"] = df["Vehicle Location"].fillna(value=df["Vehicle Location"].mode()[0])

In [12]:
df["Electric Utility"] = df["Electric Utility"].fillna(value=df["Electric Utility"].mode()[0])

In [13]:
df["Legislative District"] = df["Legislative District"].fillna(value=df["Legislative District"].mode()[0])

In [14]:
df.isnull().sum()

VIN (1-10)                                           0
County                                               0
City                                                 0
State                                                0
Postal Code                                          0
Model Year                                           0
Make                                                 0
Model                                                0
Electric Vehicle Type                                0
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0
Electric Range                                       0
Legislative District                                 0
DOL Vehicle ID                                       0
Vehicle Location                                     0
Electric Utility                                     0
2020 Census Tract                                    0
dtype: int64

### PART C — DATA INCONSISTENCY

### Task 9 — Check text consistency

In [15]:
df['State'] = df['State'].str.strip().str.title()
df["County"] = df['County'].str.strip().str.title()

### Task 10 — Investigate categorical values

In [16]:
df["State"].value_counts()

State
Wa    293432
Ca       176
Va        98
Md        47
Fl        45
Tx        44
Nv        26
Or        25
Co        25
Nc        22
Az        22
Il        18
Ga        17
Ny        13
Mo        12
Nj        11
Dc        10
Id        10
Mi         9
Al         9
Ma         8
Tn         8
Pa         7
Sc         7
Ne         7
Ri         6
Ct         6
Oh         6
Ky         5
Ks         5
Bc         5
La         5
Nm         5
Nh         4
Wi         4
In         3
Ut         3
Hi         3
Mn         3
Ae         3
Wy         2
Sd         2
Ar         2
Ok         2
Ak         2
Ia         2
Me         2
Qc         1
Gu         1
Mt         1
De         1
Ms         1
Name: count, dtype: int64

In [17]:
df["Make"].nunique()

49

In [18]:
df["Make"].unique()

array(['TESLA', 'HYUNDAI', 'NISSAN', 'FIAT', 'KIA', 'MITSUBISHI',
       'CHEVROLET', 'BMW', 'AUDI', 'JEEP', 'VOLVO', 'LEXUS', 'JAGUAR',
       'TOYOTA', 'FORD', 'GENESIS', 'RIVIAN', 'LINCOLN', 'MAZDA', 'DODGE',
       'SUBARU', 'CHRYSLER', 'SMART', 'PORSCHE', 'HONDA', 'MERCEDES-BENZ',
       'VOLKSWAGEN', 'MINI', 'GMC', 'CADILLAC', 'LUCID', 'POLESTAR',
       'BRIGHTDROP', 'FISKER', 'ACURA', 'LAND ROVER', 'ALFA ROMEO',
       'LAMBORGHINI', 'VINFAST', 'RAM', 'TH!NK', 'MULLEN AUTOMOTIVE INC.',
       'BENTLEY', 'ROLLS-ROYCE', 'WHEEGO ELECTRIC CARS', 'ASTON MARTIN',
       'FERRARI', 'AZURE DYNAMICS', 'MASERATI'], dtype=object)

In [19]:
df["County"].value_counts()

County
King          141981
Snohomish      37128
Pierce         24578
Clark          18365
Thurston       10806
               ...
Richland           1
Charles            1
Hardin             1
Davidson           1
Palm Beach         1
Name: count, Length: 257, dtype: int64

In [20]:
df["County"].nunique()

257

In [21]:
df["County"].unique()

array(['Yakima', 'Thurston', 'Kitsap', 'King', 'Snohomish', 'Stevens',
       'Walla Walla', 'Skagit', 'Island', 'Whitman', 'Chelan', 'Grant',
       'Columbia', 'Spokane', 'Kittitas', 'Cowlitz', 'Clark', 'Klickitat',
       'Jefferson', 'Clallam', 'Pierce', 'Mason', 'Franklin',
       'Grays Harbor', 'Whatcom', 'Benton', 'Lincoln', 'Douglas',
       'Pacific', 'San Juan', 'Adams', 'Okanogan', 'Multnomah', 'Lewis',
       'Wahkiakum', 'Skamania', 'Pend Oreille', 'Asotin', 'Leavenworth',
       'Ferry', 'Santa Clara', 'Fresno', 'Contra Costa', 'Carroll',
       'Saratoga', 'Morris', 'Montgomery', 'San Diego', 'Dallas',
       'El Paso', 'Shelby', 'Hamilton', 'Kern', 'Sarpy', 'San Mateo',
       'Orange', 'Wake', 'Washoe', 'San Bernardino', 'Loudoun', 'Fairfax',
       'St. Johns', 'James City', 'Polk', 'Johnson', 'Lake', 'Goochland',
       'Garfield', 'Sacramento', 'Laramie', 'Fulton', 'Kootenai', 'Duval',
       'Williamson', 'District Of Columbia', 'Nye', 'Hennepin',
       'Arlington', 'Washington', 'Madison', 'Putnam', 'Broward',
       'Onslow', 'Clay', 'Oldham', 'Dekalb', 'Jackson', 'Minnehaha',
       'Monterey', 'Maricopa', 'Riverside', 'Stafford', 'Sarasota',
       'San Francisco', 'Anne Arundel', 'Pottawatomie', 'Harnett',
       'Los Angeles', 'Bexar', 'Okaloosa', 'Newport', 'Durham', 'Fayette',
       'Cook', 'Collin', 'Virginia Beach', 'Marin', 'Alexandria',
       'Brevard', 'Houston', 'Travis', 'Suffolk', 'Greene',
       'Chesterfield', 'Norfolk', 'Frederick', 'Harford', 'Fairfield',
       'Solano', 'Stark', 'Harris', 'Chatham', 'Alameda',
       'Prince William', 'Tarrant', 'Kent', 'Larimer', 'Pulaski', 'Kings',
       'Placer', 'New York', 'Clackamas', 'Bossier', 'Onondaga',
       'New London', 'Lexington', 'Hernando', 'Medina', 'Monroe', 'Pasco',
       'Allegheny', 'Summit', 'Pinal', 'Yavapai', 'Galveston',
       'Currituck', 'Prince George', 'Burlington', 'Arapahoe',
       'Cumberland', 'Geary', 'Meade', 'Bell', 'Newport News', 'Niagara',
       'Sussex', 'Yolo', 'Muscogee', 'Anoka', 'Kane', 'Autauga',
       'Bannock', 'Allen', 'Creek', 'Albemarle', 'Middlesex', 'Deschutes',
       'Anchorage', 'Chesapeake', 'San Joaquin', 'Beauregard',
       'Portsmouth', 'Ventura', 'Coryell', 'Richmond', 'Essex',
       "Prince George'S", 'Rockingham', 'Boulder', 'Hartford',
       'Stanislaus', 'Lee', 'St. Charles', 'Queens', 'St. Landry',
       'Wayne', 'Moore', 'Latah', 'Hoke', 'Doña Ana', 'Bucks', 'Berkeley',
       'Blaine', 'Osceola', "St. Mary'S", 'Hampden', 'Baltimore', 'Maui',
       'Forsyth', 'Atlantic', 'Hillsborough', 'Hampton', 'Camden',
       'Rockwall', 'Brown', 'Hudson', 'Riley', 'Gallatin', 'Guam',
       'St. Lucie', 'Beaver', 'Macomb', 'Ada', 'Miller', 'Texas',
       'Santa Cruz', 'Pima', 'Gwinnett', 'Yuma', 'St. Clair', 'Sonoma',
       'Spartanburg', 'Miami-Dade', 'Ellis', 'Howard', 'Yuba', 'Dane',
       'Milwaukee', 'York', 'Escambia', 'Cleveland', 'Manassas', 'Denver',
       'Clatsop', 'Cuyahoga', 'Butte', 'Richland', 'Charles', 'Hardin',
       'Davidson', 'Dorchester', 'Curry', 'Honolulu', 'Manatee',
       'Bernalillo', 'Tom Green', 'Harrison', 'Nueces', 'St. Louis',
       'Washtenaw', 'Monona', 'Dale', 'Penobscot', 'Juneau', 'Davis',
       'Umatilla', 'Palm Beach'], dtype=object)

### Task 11 — Type conversion

In [22]:
df.dtypes

VIN (1-10)                                            object
County                                                object
City                                                  object
State                                                 object
Postal Code                                          float64
Model Year                                             int64
Make                                                  object
Model                                                 object
Electric Vehicle Type                                 object
Clean Alternative Fuel Vehicle (CAFV) Eligibility     object
Electric Range                                       float64
Legislative District                                 float64
DOL Vehicle ID                                         int64
Vehicle Location                                      object
Electric Utility                                      object
2020 Census Tract                                    float64
dtype: object

In [23]:
df["Model Year"]=pd.to_datetime(df["Model Year"],errors='coerce',format="%Y").dt.to_period('Y')

In [24]:
df["County"] = df["County"].astype("string")
df["City"] = df["City"].astype("string")
df["State"] = df["State"].astype("string")
df["Make"] = df["Make"].astype("string")
df["Electric Vehicle Type"] = df["Electric Vehicle Type"].astype("string")
df["Clean Alternative Fuel Vehicle (CAFV) Eligibility"] = df["Clean Alternative Fuel Vehicle (CAFV) Eligibility"].astype("string")

In [25]:
df["2020 Census Tract"] = pd.to_numeric(df["2020 Census Tract"],errors='coerce')

In [26]:
df.dtypes

VIN (1-10)                                                   object
County                                               string[python]
City                                                 string[python]
State                                                string[python]
Postal Code                                                 float64
Model Year                                            period[Y-DEC]
Make                                                 string[python]
Model                                                        object
Electric Vehicle Type                                string[python]
Clean Alternative Fuel Vehicle (CAFV) Eligibility    string[python]
Electric Range                                              float64
Legislative District                                        float64
DOL Vehicle ID                                                int64
Vehicle Location                                             object
Electric Utility                                             object
2020 Census Tract                                           float64
dtype: object

## PART D — DUPLICATES

### Task 12 — Identify duplicate rows

In [27]:
df.duplicated().sum()

np.int64(0)

## PART E — OUTLIERS

### Task 15 — Identify suitable numerical columns

In [28]:
num = ["Electric Range", "2020 Census Tract"]

### Task 16 — Detect outliers using IQR

In [29]:
Q1 = df['Electric Range'].quantile(0.25)
Q3 = df['Electric Range'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
print("Lower Bound:", lower)
print("Upper Bound:", upper)
df_iqr = df[
(df['Electric Range'] >= lower) &
(df['Electric Range'] <= upper)
]
print(df_iqr.head())

Lower Bound: -48.0
Upper Bound: 80.0
    VIN (1-10)    County          City State  Postal Code Model Year  \
5   JN1AZ0CP6B    Kitsap  Port Orchard    Wa      98366.0       2011
8   7SAYGDEE0P    Yakima        Yakima    Wa      98901.0       2023
12  JA4T5VA92R  Thurston          Yelm    Wa      98597.0       2024
21  5UXKT0C5XG  Thurston       Olympia    Wa      98512.0       2016
23  5YJYGAEE2M   Stevens      Chewelah    Wa      99109.0       2021

          Make      Model                   Electric Vehicle Type  \
5       NISSAN       LEAF          Battery Electric Vehicle (BEV)
8        TESLA    MODEL Y          Battery Electric Vehicle (BEV)
12  MITSUBISHI  OUTLANDER  Plug-in Hybrid Electric Vehicle (PHEV)
21         BMW         X5  Plug-in Hybrid Electric Vehicle (PHEV)
23       TESLA    MODEL Y          Battery Electric Vehicle (BEV)

    Clean Alternative Fuel Vehicle (CAFV) Eligibility  Electric Range  \
5             Clean Alternative Fuel Vehicle Eligible            73.0
8   Eligibility unknown as battery range has not b...             0.0
12            Clean Alternative Fuel Vehicle Eligible            38.0
21              Not eligible due to low battery range            14.0
23  Eligibility unknown as battery range has not b...             0.0

    Legislative District  DOL Vehicle ID             Vehicle Location  \
5                   26.0       294761365   POINT (-122.63848 47.5414)
8                   15.0       238311293  POINT (-120.50729 46.60464)
12                   2.0       261583066  POINT (-122.60735 46.94239)
21                  35.0       239283544  POINT (-123.04078 46.94792)
23                   7.0       268743149  POINT (-117.71555 48.28136)

          Electric Utility  2020 Census Tract
5   PUGET SOUND ENERGY INC       5.303509e+10
8               PACIFICORP       5.307700e+10
12  PUGET SOUND ENERGY INC       5.306701e+10
21  PUGET SOUND ENERGY INC       5.306701e+10
23        CITY OF CHEWELAH       5.306595e+10

In [30]:
Q1 = df['2020 Census Tract'].quantile(0.25)
Q3 = df['2020 Census Tract'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
print("Lower Bound:", lower)
print("Upper Bound:", upper)
df_iqr = df[
(df['2020 Census Tract'] >= lower) &
(df['2020 Census Tract'] <= upper)
]
print(df_iqr.head())

Lower Bound: 53001614238.5
Upper Bound: 53085335474.5
   VIN (1-10)    County      City State  Postal Code Model Year     Make  \
0  5YJ3E1EA5L    Yakima    Yakima    Wa      98908.0       2020    TESLA
1  5YJ3E1EA9K  Thurston   Olympia    Wa      98502.0       2019    TESLA
2  5YJSA1H22F    Kitsap  Kingston    Wa      98346.0       2015    TESLA
3  KM8K33AG7L      King   Seattle    Wa      98107.0       2020  HYUNDAI
4  5YJ3E1EB1K    Yakima    Yakima    Wa      98902.0       2019    TESLA

     Model           Electric Vehicle Type  \
0  MODEL 3  Battery Electric Vehicle (BEV)
1  MODEL 3  Battery Electric Vehicle (BEV)
2  MODEL S  Battery Electric Vehicle (BEV)
3     KONA  Battery Electric Vehicle (BEV)
4  MODEL 3  Battery Electric Vehicle (BEV)

  Clean Alternative Fuel Vehicle (CAFV) Eligibility  Electric Range  \
0           Clean Alternative Fuel Vehicle Eligible           266.0
1           Clean Alternative Fuel Vehicle Eligible           220.0
2           Clean Alternative Fuel Vehicle Eligible           208.0
3           Clean Alternative Fuel Vehicle Eligible           258.0
4           Clean Alternative Fuel Vehicle Eligible           220.0

   Legislative District  DOL Vehicle ID             Vehicle Location  \
0                  14.0       102765120  POINT (-120.60272 46.59656)
1                  22.0       326796641  POINT (-122.92018 47.04575)
2                  23.0       166294418   POINT (-122.4977 47.79802)
3                  43.0       127090015  POINT (-122.38591 47.67597)
4                  14.0       272512824  POINT (-120.51904 46.59782)

                               Electric Utility  2020 Census Tract
0                                    PACIFICORP       5.307700e+10
1                        PUGET SOUND ENERGY INC       5.306701e+10
2                        PUGET SOUND ENERGY INC       5.303509e+10
3  CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)       5.303300e+10
4                                    PACIFICORP       5.307700e+10

## PART F — OUTLIER HANDLING

### Task 20 — Decide how to handle the outliers

I don't want to remove

### Task 21 — Apply outlier capping

In [31]:
import numpy as np

In [32]:
Q1 = df['Electric Range'].quantile(0.25)
Q3 = df['Electric Range'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df['Electric Range'] = np.where(
    df['Electric Range'] > upper,
    upper,
    np.where(
        df['Electric Range'] < lower,
        lower,
        df['Electric Range']
    )
)

### Task 22 — Apply log transformation

In [33]:
np.log1p(df["Electric Range"])

0         4.394449
1         4.394449
2         4.394449
3         4.394449
4         4.394449
            ...
294188    3.737670
294189    4.394449
294190    0.000000
294191    3.258097
294192    4.394449
Name: Electric Range, Length: 294193, dtype: float64

## PART G — BASIC DATA ANALYSIS AFTER CLEANING

### Task 23 — Most common manufacturers

In [34]:
df["Make"].value_counts().index[0]

'TESLA'

### Task 24 — Most common vehicle models

In [35]:
df["Model"].value_counts().index[0]

'MODEL Y'

### Task 25 — BEV vs PHEV

In [36]:
df["Electric Vehicle Type"].value_counts()

Electric Vehicle Type
Battery Electric Vehicle (BEV)            237567
Plug-in Hybrid Electric Vehicle (PHEV)     56626
Name: count, dtype: Int64

### Task 26 — Model-year analysis

In [37]:
# What is the earliest model year?
min(df["Model Year"])

Period('1999', 'Y-DEC')

In [38]:
# What is the latest model year?
max(df["Model Year"])

Period('2027', 'Y-DEC')

In [39]:
# Which model years occur most frequently?
df["Model Year"].value_counts().head(1)

Model Year
2023    60689
Freq: Y-DEC, Name: count, dtype: int64

### Task 27 — Electric range analysis

In [40]:
# What is the average electric range?
df["Electric Range"].sum()/len(df["Electric Range"])

np.float64(18.33457968068581)

In [41]:
# What is the minimum?
min(df["Electric Range"])

0.0

In [42]:
# What is the maximum?
max(df["Electric Range"])

80.0

## PART H — FINAL VALIDATION

In [43]:
df.to_csv("cleaned_ev_data.csv",index=False)

## Task 31 — Write a cleaning report

There are small number of null values.
Which missing-value techniques you used = median, mode
I handled using IQR test for outliers.
There is no duplicated values.

# Task

In [48]:
gp = df.groupby("Make")["Electric Vehicle Type"].value_counts()

In [49]:
gp

Make                  Electric Vehicle Type
ACURA                 Battery Electric Vehicle (BEV)             357
ALFA ROMEO            Plug-in Hybrid Electric Vehicle (PHEV)      98
ASTON MARTIN          Plug-in Hybrid Electric Vehicle (PHEV)       1
AUDI                  Battery Electric Vehicle (BEV)            4068
                      Plug-in Hybrid Electric Vehicle (PHEV)    2032
                                                                ...
VINFAST               Battery Electric Vehicle (BEV)               6
VOLKSWAGEN            Battery Electric Vehicle (BEV)            7893
VOLVO                 Plug-in Hybrid Electric Vehicle (PHEV)    5153
                      Battery Electric Vehicle (BEV)            2775
WHEEGO ELECTRIC CARS  Plug-in Hybrid Electric Vehicle (PHEV)       2
Name: count, Length: 70, dtype: int64

In [50]:
df.columns

Index(['VIN (1-10)', 'County', 'City', 'State', 'Postal Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Legislative District', 'DOL Vehicle ID', 'Vehicle Location',
       'Electric Utility', '2020 Census Tract'],
      dtype='object')

In [51]:
print(df["Electric Range"].sum())
print(df["Electric Range"].median())
print(df["Electric Range"].mean())

5393905.0
0.0
18.33457968068581

In [52]:
print(df["Model"].mode())

0    MODEL Y
Name: Model, dtype: object